# Generated by Django 3.1.5 on 2022-02-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_tb',
            name='phone',
            field=models.CharField(default='no phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller_tb',
            name='image',
            field=models.FileField(default='pending', upload_to=''),
        ),
    ]
