# Generated by Django 3.1.5 on 2022-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20220217_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_tb',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
