# Generated by Django 3.1.5 on 2022-02-21 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0005_category_tb'),
        ('seller', '0003_seller_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.FileField(upload_to='')),
                ('price', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=40)),
                ('stock', models.CharField(max_length=20)),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_admin.category_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_tb')),
            ],
        ),
    ]
