# Generated by Django 3.1.5 on 2022-03-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_tracking_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.IntegerField(),
        ),
    ]
