# Generated by Django 3.1.5 on 2022-02-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admin_tb',
            new_name='login_tb',
        ),
    ]
