# Generated by Django 3.1.5 on 2022-02-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_admin', '0002_auto_20220218_1245'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login_tb',
        ),
    ]
