# Generated by Django 3.1.5 on 2022-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_tb',
            name='phone',
            field=models.CharField(default='nophone number', max_length=20),
        ),
    ]
