# Generated by Django 3.1.5 on 2022-02-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20220225_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_tb',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cart_tb',
            name='contactno',
            field=models.IntegerField(),
        ),
    ]
