# Generated by Django 3.1.5 on 2022-02-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_product_tb'),
        ('Buyer', '0005_auto_20220225_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingaddress', models.CharField(max_length=40)),
                ('quantity', models.CharField(max_length=20)),
                ('totalprice', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Buyer.buyer_tb')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product_tb')),
                ('sellerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller_tb')),
            ],
        ),
    ]
